# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_plugins: []
additional_repos: []
black: true
check_commit_message: true
check_gettext: true
check_manifest: true
check_openapi_schema: true
check_stray_pulpcore_imports: true
cherry_pick_automation: false
coverage: false
deploy_client_to_pypi: true
deploy_client_to_rubygems: true
deploy_daily_client_to_pypi: true
deploy_daily_client_to_rubygems: true
deploy_to_pypi: true
docker_fixtures: false
docs_test: true
issue_tracker: redmine
plugin_app_label: maven
plugin_camel: PulpMaven
plugin_camel_short: Maven
plugin_caps: PULP_MAVEN
plugin_caps_short: MAVEN
plugin_dash: pulp-maven
plugin_dash_short: maven
plugin_default_branch: master
plugin_name: pulp_maven
plugin_snake: pulp_maven
publish_docs_to_pulpprojectdotorg: false
pulp_settings: null
pulpcore_branch: master
pulpcore_pip_version_specifier: null
pulpprojectdotorg_key_id: null
pydocstyle: true
pypi_username: pulp
redmine_project: maven-plugin
release_user: pulpbot
stable_branch: null
test_bindings: true
test_cli: false
test_performance: false
test_released_plugin_with_next_pulpcore_release: false
test_s3: false
travis_addtl_services: []
travis_notifications: None
update_redmine: false
upgrade_range: []

